# Method 1: 加Flatten Layer

In [8]:
import tensorflow as tf

len(tf.keras.datasets.mnist.load_data())

2

In [12]:
import tensorflow as tf

(x_train, y_train),(x_test, y_test) = tf.keras.datasets.mnist.load_data()
print(x_train.dtype)
x_train, x_test = x_train / 255, x_test / 255
# x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train.dtype)
print('-' * 30)

model = tf.keras.models.Sequential([
#   tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Flatten(), 
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax') # predict 0~9
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5) # batch_size: If unspecified, `batch_size` will default to 32. e.g. 60000/32=1875
print('-' * 30)
model.evaluate(x_test, y_test)

uint8
float64
------------------------------
Epoch 1/5
1875/1875 [==============================] - 2s 809us/step - loss: 0.2971 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 2s 867us/step - loss: 0.1459 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 2s 882us/step - loss: 0.1076 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 1s 790us/step - loss: 0.0897 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 1s 798us/step - loss: 0.0757 - accuracy: 0.9764
------------------------------
313/313 [==============================] - 0s 633us/step - loss: 0.0756 - accuracy: 0.9762


[0.07562687993049622, 0.9761999845504761]

In [13]:
model.fit?

In [14]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [15]:
x_train.shape

(60000, 28, 28)

In [16]:
x_train.min(), x_train.max()

(0.0, 1.0)

In [17]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [18]:
y_train.shape

(60000,)

In [19]:
y_train.min(), y_train.max()

(0, 9)

In [20]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 128)               100480    
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [22]:
# 預測(prediction)
predictions = model.predict_classes(x_test)
# get prediction result
print('prediction:', predictions[0:20])
print('actual    :', y_test[0:20])

prediction: [7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
actual    : [7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [23]:
model.predict(x_test)

array([[4.7449507e-09, 9.0940855e-09, 1.3607737e-06, ..., 9.9994910e-01,
        2.8966355e-07, 1.2204419e-05],
       [2.3979385e-09, 2.0073283e-05, 9.9997640e-01, ..., 1.2538024e-14,
        1.2899616e-07, 1.3687514e-12],
       [4.4382088e-07, 9.9813348e-01, 1.1107184e-04, ..., 6.3358148e-04,
        9.8250329e-04, 1.2391833e-06],
       ...,
       [1.5242387e-11, 2.5786655e-09, 5.8099872e-11, ..., 3.1626746e-06,
        2.8559782e-07, 1.7636038e-03],
       [2.5208668e-09, 6.0477034e-10, 1.3624531e-12, ..., 5.7252830e-10,
        2.5658572e-05, 5.9766525e-10],
       [7.8144996e-07, 8.7752618e-12, 4.0777036e-07, ..., 2.6657311e-13,
        8.2451296e-10, 1.0121198e-09]], dtype=float32)

In [24]:
import numpy as np
print(np.argmax(model.predict(x_test), axis = 1)[:20])

[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]


In [27]:
# del model

# Method 2: 不加Flatten Layer的話就需要手動Flatten (reshape dataset)

In [25]:
x_train.shape

(60000, 28, 28)

In [26]:
x_test.shape

(10000, 28, 28)

In [27]:
# 將 input data 由3維轉為2維
X_train_2D = x_train.reshape(x_train.shape[0], -1).astype('float32')  
X_test_2D = x_test.reshape(x_test.shape[0], -1).astype('float32')
X_train_2D.shape

(60000, 784)

In [28]:
model2 = tf.keras.models.Sequential([
#   tf.keras.layers.Dense(units=256, input_dim=784, activation='relu'), # units=128, 256
  tf.keras.layers.Dense(units=256, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax') # predict 0~9
])

model2.compile(optimizer='adam',
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'])

# model2.fit(X_train_2D, y_train, epochs=5) # batch_size: If unspecified, `batch_size` will default to 32. e.g. 60000/32=1875
model2.fit(X_train_2D, y_train, epochs=5, batch_size = 64) # 60000/64=937.5
model2.evaluate(X_test_2D, y_test)

Epoch 1/5
938/938 [==============================] - 1s 1ms/step - loss: 0.2828 - accuracy: 0.9179
Epoch 2/5
938/938 [==============================] - 1s 1ms/step - loss: 0.1254 - accuracy: 0.9624
Epoch 3/5
938/938 [==============================] - 1s 1ms/step - loss: 0.0895 - accuracy: 0.9735
Epoch 4/5
938/938 [==============================] - 1s 1ms/step - loss: 0.0692 - accuracy: 0.9784
Epoch 5/5
313/313 [==============================] - 0s 605us/step - loss: 0.0704 - accuracy: 0.9774


[0.07039733231067657, 0.977400004863739]

In [29]:
model2.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 256)               200960    
_________________________________________________________________
dropout_4 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 10)                2570      
Total params: 203,530
Trainable params: 203,530
Non-trainable params: 0
_________________________________________________________________


# Method 3: Use categorical_crossentropy

In [32]:
from keras.utils import to_categorical
y_train_catego = to_categorical(y_train)
y_test_catego = to_categorical(y_test)
y_train_catego

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [35]:
y_train_catego.shape

(60000, 10)

In [36]:
model3 = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(), 
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax') # predict 0~9
])

model3.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model3.fit(x_train, y_train_catego, epochs=5) # batch_size: If unspecified, `batch_size` will default to 32. e.g. 60000/32=1875
print('-' * 30)
model3.evaluate(x_test, y_test_catego)

Epoch 1/5
1875/1875 [==============================] - 1s 783us/step - loss: 0.2916 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 2s 821us/step - loss: 0.1448 - accuracy: 0.9569
Epoch 3/5
1875/1875 [==============================] - 1s 768us/step - loss: 0.1090 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 1s 770us/step - loss: 0.0885 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 2s 824us/step - loss: 0.0766 - accuracy: 0.9765
------------------------------
313/313 [==============================] - 0s 604us/step - loss: 0.0761 - accuracy: 0.9759


[0.07609990984201431, 0.9758999943733215]