# Method 1: 加Flatten Layer

In [9]:
import tensorflow as tf

(x_train, y_train),(x_test, y_test) = tf.keras.datasets.mnist.load_data()
print(x_train.dtype)
x_train, x_test = x_train / 255, x_test / 255
# x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train.dtype)
print('-' * 30)

model = tf.keras.models.Sequential([
#   tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Flatten(), 
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax') # predict 0~9
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5) # batch_size: If unspecified, `batch_size` will default to 32. e.g. 60000/32=1875
model.evaluate(x_test, y_test)

uint8
float64
------------------------------
Epoch 1/5
1875/1875 [==============================] - 2s 902us/step - loss: 0.2965 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 1s 789us/step - loss: 0.1411 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 2s 808us/step - loss: 0.1073 - accuracy: 0.9684
Epoch 4/5
1875/1875 [==============================] - 2s 859us/step - loss: 0.0890 - accuracy: 0.9728
Epoch 5/5
313/313 [==============================] - 0s 567us/step - loss: 0.0757 - accuracy: 0.9775


[0.07567745447158813, 0.9775000214576721]

In [67]:
model.fit?

In [76]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [77]:
x_train.shape

(60000, 28, 28)

In [78]:
x_train.min(), x_train.max()

(0.0, 1.0)

In [79]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [80]:
y_train.shape

(60000,)

In [81]:
y_train.min(), y_train.max()

(0, 9)

In [82]:
model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_13 (Flatten)         (None, 784)               0         
_________________________________________________________________
dense_34 (Dense)             (None, 128)               100480    
_________________________________________________________________
dense_35 (Dense)             (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [83]:
# 預測(prediction)
predictions = model.predict_classes(x_test)
# get prediction result
print('prediction:', predictions[0:20])
print('actual    :', y_test[0:20])

prediction: [7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
actual    : [7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [84]:
model.predict(x_test)

array([[7.0000792e-09, 4.4285889e-10, 1.7473866e-07, ..., 9.9999368e-01,
        4.0929504e-09, 4.5104284e-07],
       [3.5801506e-09, 1.9335057e-06, 9.9999785e-01, ..., 1.5157914e-14,
        9.7215299e-08, 1.3903909e-13],
       [2.4187077e-07, 9.9800414e-01, 3.5475448e-04, ..., 9.6906041e-04,
        3.6280864e-04, 8.8314382e-06],
       ...,
       [5.8166417e-13, 1.2648987e-11, 3.4571285e-13, ..., 3.4770212e-05,
        1.3657372e-07, 6.1466908e-06],
       [2.2066642e-08, 7.3356758e-11, 2.0115314e-10, ..., 2.6802701e-07,
        1.7512804e-05, 3.5135067e-10],
       [1.9025613e-06, 1.6692077e-12, 6.4399563e-07, ..., 1.1053847e-13,
        4.0016215e-10, 1.6874937e-11]], dtype=float32)

In [85]:
import numpy as np
print(np.argmax(model.predict(x_test), axis = 1)[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [27]:
# del model

# Method 2: 不加Flatten Layer的話就需要手動Flatten (reshape dataset)

In [86]:
x_train.shape

(60000, 28, 28)

In [87]:
x_test.shape

(10000, 28, 28)

In [88]:
# 將 input data 由3維轉為2維
X_train_2D = x_train.reshape(x_train.shape[0], -1).astype('float32')  
X_test_2D = x_test.reshape(x_test.shape[0], -1).astype('float32')
X_train_2D.shape

(60000, 784)

In [90]:
model2 = tf.keras.models.Sequential([
#   tf.keras.layers.Dense(units=256, input_dim=784, activation='relu'), # units=128, 256
  tf.keras.layers.Dense(units=256, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax') # predict 0~9
])

model2.compile(optimizer='adam',
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'])

# model2.fit(X_train_2D, y_train, epochs=5) # batch_size: If unspecified, `batch_size` will default to 32. e.g. 60000/32=1875
model2.fit(X_train_2D, y_train, epochs=5, batch_size = 64) # 60000/64=937.5
model2.evaluate(X_test_2D, y_test)

Epoch 1/5
938/938 [==============================] - 1s 1ms/step - loss: 0.2861 - accuracy: 0.9182
Epoch 2/5
938/938 [==============================] - 1s 1ms/step - loss: 0.1281 - accuracy: 0.9626
Epoch 3/5
938/938 [==============================] - 1s 1ms/step - loss: 0.0925 - accuracy: 0.9717
Epoch 4/5
938/938 [==============================] - 1s 1ms/step - loss: 0.0726 - accuracy: 0.9779
Epoch 5/5
313/313 [==============================] - 0s 511us/step - loss: 0.0676 - accuracy: 0.9792


[0.06761792302131653, 0.979200005531311]

In [91]:
model2.summary()

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_38 (Dense)             (None, 256)               200960    
_________________________________________________________________
dropout_14 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_39 (Dense)             (None, 10)                2570      
Total params: 203,530
Trainable params: 203,530
Non-trainable params: 0
_________________________________________________________________
