In [33]:
from sklearn import datasets #導入內置資料集模組
from sklearn.neighbors import KNeighborsClassifier #導入sklearn.neighbors模組中KNN類
import numpy as np
import pandas as pd

In [34]:
ds = datasets.load_iris()
type(ds)

sklearn.utils.Bunch

In [35]:
ds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [36]:
print(ds.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [37]:
print(ds.target_names)

['setosa' 'versicolor' 'virginica']


In [38]:
ds.feature_names, type(ds.feature_names)

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 list)

In [39]:
ds.data, type(ds.data)

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [40]:
ds.data[:, [2, 3]]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [41]:
ds.data[:, 2: 4]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [42]:
X = pd.DataFrame(ds.data, columns = ds.feature_names)
y = ds.target

In [43]:
X, type(X), X.shape, X.ndim, X.size

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 pandas.core.frame.DataFr

In [44]:
y, type(y), y.shape, y.ndim, y.size

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 numpy.ndarray,
 (150,),
 1,
 150)

In [45]:
X['sepal length (cm)']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [46]:
X['sepal length (cm)'].mean()

5.843333333333335

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [48]:
train_test_split?

In [49]:
X_test, type(X_test), X_test.shape, X_test.ndim, X_test.size

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 80                 5.5               2.4                3.8               1.1
 122                7.7               2.8                6.7               2.0
 3                  4.6               3.1                1.5               0.2
 147                6.5               3.0                5.2               2.0
 102                7.1               3.0                5.9               2.1
 114                5.8               2.8                5.1               2.4
 146                6.3               2.5                5.0               1.9
 81                 5.5               2.4                3.7               1.0
 69                 5.6               2.5                3.9               1.1
 28                 5.2               3.4                1.4               0.2
 113                5.7               2.5                5.0               2.0
 124                6.7               3.3           

In [50]:
y_test, type(y_test), y_test.shape, y_test.ndim, y_test.size

(array([1, 2, 0, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2,
        1, 2, 1, 1, 2, 0, 0, 0]),
 numpy.ndarray,
 (30,),
 1,
 30)

In [51]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [52]:
knn.score(X_test, y_test)

0.9666666666666667

In [53]:
# knn2 = KNeighborsClassifier(n_neighbors=5, weights='distance')
knn2 = KNeighborsClassifier(n_neighbors=21, weights='distance')
knn2.fit(X_train, y_train)
knn2.score(X_test, y_test)

0.9666666666666667

In [54]:
knn.effective_metric_

'euclidean'

In [55]:
knn.classes_

array([0, 1, 2])

In [56]:
?? KNeighborsClassifier

## 查詢最近N個點及其index，可以用於推薦系統 (Recommender System)
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier.kneighbors

In [57]:
knn.kneighbors?

In [58]:
X_test[0:1]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
80                5.5               2.4                3.8               1.1

In [59]:
Result_kneighbors = knn.kneighbors(X=X_test[0:1], n_neighbors=3, return_distance=True)
print(Result_kneighbors)
print(type(Result_kneighbors))
print(len(Result_kneighbors))
print(type(Result_kneighbors[1]))

(array([[0.3       , 0.3       , 0.42426407]]), array([[17, 46, 22]], dtype=int64))
<class 'tuple'>
2
<class 'numpy.ndarray'>


In [60]:
Result_kneighbors = knn.kneighbors(X=X_test[0:2], n_neighbors=3, return_distance=True)
print(Result_kneighbors)
print(type(Result_kneighbors))
print(len(Result_kneighbors))
print(type(Result_kneighbors[1]))

(array([[0.3       , 0.3       , 0.42426407],
       [0.26457513, 0.41231056, 0.60827625]]), array([[ 17,  46,  22],
       [ 76, 116,  75]], dtype=int64))
<class 'tuple'>
2
<class 'numpy.ndarray'>


In [61]:
knn.kneighbors(X=X_test[0:1], n_neighbors=3, return_distance=False)

array([[17, 46, 22]], dtype=int64)

In [62]:
knn.kneighbors(X=X_test[0:1], n_neighbors=5)

(array([[0.3       , 0.3       , 0.42426407, 0.42426407, 0.4472136 ]]),
 array([[ 46,  17,  22,  78, 107]], dtype=int64))

# Develop k-Nearest Neighbors in Python From Scratch
https://machinelearningmastery.com/tutorial-to-implement-k-nearest-neighbors-in-python-from-scratch/

In [71]:
# Example of getting neighbors for an instance
from math import sqrt

# calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
    distance = 0.0
#     for i in range(len(row1)-1): # -1: 因為數據最後一筆是 target
#         distance += (row1[i] - row2[i])**2
    distance = sum((np.array(row1[:-1]) - np.array(row2[:-1]))**2)
    return sqrt(distance)

# Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
	distances = list()
	for train_row in train:
		dist = euclidean_distance(test_row, train_row)
		distances.append((train_row, dist))
	distances.sort(key=lambda tup: tup[1]) # 針對 distances 中的 dist 做排序
	neighbors = list()
	for i in range(num_neighbors):
		neighbors.append(distances[i][0])
	return neighbors

# Test distance function
dataset = [[2.7810836,2.550537003,0],
	[1.465489372,2.362125076,0],
	[3.396561688,4.400293529,0],
	[1.38807019,1.850220317,0],
	[3.06407232,3.005305973,0],
	[7.627531214,2.759262235,1],
	[5.332441248,2.088626775,1],
	[6.922596716,1.77106367,1],
	[8.675418651,-0.242068655,1],
	[7.673756466,3.508563011,1]]
neighbors = get_neighbors(dataset, dataset[0], 3)
for neighbor in neighbors:
	print(neighbor)

[2.7810836, 2.550537003, 0]
[3.06407232, 3.005305973, 0]
[1.465489372, 2.362125076, 0]


In [74]:
max(neighbors)

[3.06407232, 3.005305973, 0]

In [79]:
max(neighbors, key = lambda r: r[2])

[2.7810836, 2.550537003, 0]

In [84]:
# testList = [0, 5, 2, 1, 0, 5, 5]
testList = [0, 5, 2, 1, 0, 5, 5, 0, 0, 0]
print(set(testList))
max(set(testList), key=testList.count)

{0, 1, 2, 5}


0

In [90]:
# Make a classification prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors] # 取出 Target
#     prediction = max(output_values)
    prediction = max(set(output_values), key=output_values.count)
    return prediction

In [92]:
# Example of making predictions
prediction = predict_classification(dataset, dataset[0], 3)
print('Expected %d, Got %d.' % (dataset[0][-1], prediction))

Expected 0, Got 0.


In [95]:
testList = [0, 1, 1, 1, 1, 1, 2, 3, 4, 2, 2, 1, 4, 4, 1, 1, 1, 1, 1]
set_testList = set(testList)
print(set_testList)
print(max(testList))
print(max(set(testList)))
print(max(set(testList), key=testList.count))
print('-' * 50)
print(max(testList, key=testList.count))
print(max(testList, key=lambda d: testList.count(d)))
print(max(testList, key=lambda d: d%3))
print(testList.count)

{0, 1, 2, 3, 4}
4
4
1
--------------------------------------------------
1
1
2
<built-in method count of list object at 0x000001F9FF8C0A40>


In [97]:
# The count() method returns the number of times the specified element appears in the list.
print('The count of 1 is:', testList.count(0))
print('The count of 1 is:', testList.count(1))
print('The count of 2 is:', testList.count(2))
print('The count of 3 is:', testList.count(3))
print('The count of 4 is:', testList.count(4))
print('The count of 1 is:', testList.count(5))

The count of 1 is: 1
The count of 1 is: 11
The count of 2 is: 3
The count of 3 is: 1
The count of 4 is: 3
The count of 1 is: 0


In [98]:
testList2 = [('Jeff', 100), ('Andy', 95), ('Chris', 96), ('Spark', 80), ('Peter', 65)]
maxp = max(testList2, key=lambda d:d[1])
print(maxp)
print(type(maxp))

('Jeff', 100)
<class 'tuple'>


# Logistic Regression

In [100]:
from sklearn.linear_model import LogisticRegression
LogisticRegression?
clf = LogisticRegression(C=100.0, random_state=1)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  to using ``penalty='l1'``. For ``0 < l1_ratio <1``, the penalty is a


1.0

In [101]:
clf2 = LogisticRegression(C=0.1, random_state=1)
clf2.fit(X_train, y_train)
clf2.score(X_test, y_test)

0.9

# Performance Metric

In [102]:
y_pred= clf2.predict(X_test)
print(y_test)
print(y_pred)
print(y_test != y_pred)
print('----------')
print('Misclassified samples: %d' % (y_test!= y_pred).sum())
print('Misclassified samples:', (y_test!= y_pred).sum())

[1 2 0 2 2 2 2 1 1 0 2 2 2 1 2 0 2 1 1 0 2 2 1 2 1 1 2 0 0 0]
[1 2 0 2 2 2 2 1 1 0 1 2 2 1 2 0 2 1 1 0 2 1 1 2 1 1 1 0 0 0]
[False False False False False False False False False False  True False
 False False False False False False False False False  True False False
 False False  True False False False]
----------
Misclassified samples: 3
Misclassified samples: 3


In [103]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.90


In [104]:
acc = np.average(y_test == y_pred)
print('Accuracy:', acc)

Accuracy: 0.9


In [108]:
# Calculate AUC
clf2.predict_proba?
y_scores = clf2.predict_proba(X_test) # Probability estimates.
print(type(y_scores))

print('\n----------y_scores----------')
print(y_scores)

print('\n----------y_scores[:,1]----------')
print(y_scores[:,1])

print('\n----------y_scores[:][1]----------')
print(y_scores[:][1])

print('\n----------y_scores[1]----------')
print(y_scores[1])

print('\n----------y_scores[2][1]----------')
print(y_scores[2][1])

<class 'numpy.ndarray'>

----------y_scores----------
[[1.45750544e-01 7.43351816e-01 1.10897640e-01]
 [3.37450240e-04 1.05297849e-01 8.94364700e-01]
 [8.90273106e-01 1.08612874e-01 1.11401965e-03]
 [1.13588920e-02 3.64515511e-01 6.24125597e-01]
 [2.15395222e-03 1.95854426e-01 8.01991622e-01]
 [1.29270798e-02 3.84489189e-01 6.02583731e-01]
 [1.51403928e-02 4.84836463e-01 5.00023144e-01]
 [1.68004842e-01 7.38278887e-01 9.37162712e-02]
 [1.33070319e-01 7.38056219e-01 1.28873462e-01]
 [9.03116059e-01 9.56564116e-02 1.22752917e-03]
 [1.84732710e-02 5.12147912e-01 4.69378817e-01]
 [4.30800411e-03 2.26018690e-01 7.69673306e-01]
 [2.12586848e-03 1.59929858e-01 8.37944274e-01]
 [4.20796174e-02 5.12888663e-01 4.45031720e-01]
 [8.12970470e-03 3.01566077e-01 6.90304218e-01]
 [8.71496655e-01 1.26989094e-01 1.51425007e-03]
 [9.13307781e-03 4.59344574e-01 5.31522349e-01]
 [3.45505324e-02 5.22757637e-01 4.42691830e-01]
 [4.27486886e-02 5.98811840e-01 3.58439472e-01]
 [9.06623324e-01 9.17528324e-02 1.

In [109]:
y_test

array([1, 2, 0, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2,
       1, 2, 1, 1, 2, 0, 0, 0])

In [114]:
label = 0
y_test_label = np.where(y_test == label, 1, 0)
y_test_label

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1])

In [116]:
y_scores

array([[1.45750544e-01, 7.43351816e-01, 1.10897640e-01],
       [3.37450240e-04, 1.05297849e-01, 8.94364700e-01],
       [8.90273106e-01, 1.08612874e-01, 1.11401965e-03],
       [1.13588920e-02, 3.64515511e-01, 6.24125597e-01],
       [2.15395222e-03, 1.95854426e-01, 8.01991622e-01],
       [1.29270798e-02, 3.84489189e-01, 6.02583731e-01],
       [1.51403928e-02, 4.84836463e-01, 5.00023144e-01],
       [1.68004842e-01, 7.38278887e-01, 9.37162712e-02],
       [1.33070319e-01, 7.38056219e-01, 1.28873462e-01],
       [9.03116059e-01, 9.56564116e-02, 1.22752917e-03],
       [1.84732710e-02, 5.12147912e-01, 4.69378817e-01],
       [4.30800411e-03, 2.26018690e-01, 7.69673306e-01],
       [2.12586848e-03, 1.59929858e-01, 8.37944274e-01],
       [4.20796174e-02, 5.12888663e-01, 4.45031720e-01],
       [8.12970470e-03, 3.01566077e-01, 6.90304218e-01],
       [8.71496655e-01, 1.26989094e-01, 1.51425007e-03],
       [9.13307781e-03, 4.59344574e-01, 5.31522349e-01],
       [3.45505324e-02, 5.22757

In [115]:
from sklearn.metrics import roc_auc_score
# auc = roc_auc_score(y_test, y_scores[:,label])
auc = roc_auc_score(y_test_label, y_scores[:,label])
print('AUC: ' + str(auc))

AUC: 1.0
