In [1]:
from sklearn import datasets  
#導入內置資料集模組                      
from sklearn.neighbors import KNeighborsClassifier 
#導入sklearn.neighbors模組中KNN類
import numpy as np 
np.random.seed(0)  
#設置隨機種子，不設置的話預設是按系統時間作為參數，因此每次調用隨機模組時產生的亂數都不一樣設置後每次產生的一樣
iris=datasets.load_iris() 
#導入鳶尾花的資料集，iris是一個類似於結構體的東西，內部有樣本資料，如果是監督學習還有標籤資料

In [2]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
np.random.permutation(10)

array([2, 3, 8, 4, 5, 1, 0, 6, 9, 7])

In [8]:
np.random.permutation([2, 3, 8, 4, 5, 1, 0, 6, 9, 7])

array([3, 9, 7, 1, 8, 0, 4, 6, 5, 2])

In [9]:
iris_x=iris.data   
#樣本資料150*4二維資料，代表150個樣本，每個樣本4個屬性分別為花瓣和花萼的長、寬
iris_y=iris.target  
#長150的陣列，樣本資料的標籤
indices = np.random.permutation(len(iris_x))
#permutation接收一個數作為參數(150),產生一個0-149一維陣列，只不過是隨機打亂的，當然她也可以接收一個一維陣列作為參數，結果是直接對這個陣列打亂
iris_x_train = iris_x[indices[:-10]]
#隨機選取140個樣本作為訓練資料集
iris_y_train = iris_y[indices[:-10]] 
#並且選取這140個樣本的標籤作為訓練資料集的標籤
iris_x_test  = iris_x[indices[-10:]]
#剩下的10個樣本作為測試資料集
iris_y_test  = iris_y[indices[-10:]] 
#並且把剩下10個樣本對應標籤作為測試資料集的標籤

iris_x_test

array([[4.4, 3.2, 1.3, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [5.7, 2.6, 3.5, 1. ],
       [5.1, 3.5, 1.4, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [5.9, 3. , 5.1, 1.8],
       [6.4, 2.8, 5.6, 2.1]])

In [10]:
iris_x, type(iris_x), iris_x.shape, iris_x.ndim, iris_x.size

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [11]:
Min_sepal_length = iris_x[:, 0].min()
Max_sepal_length = iris_x[:, 0].max()
Mean_sepal_length = iris_x[:, 0].mean()
SD_sepal_length = iris_x[:, 0].std()

Min_sepal_length, Max_sepal_length, Mean_sepal_length, SD_sepal_length

(4.3, 7.9, 5.843333333333334, 0.8253012917851409)

In [12]:
iris_y, type(iris_y), iris_y.shape, iris_y.ndim, iris_y.size

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 numpy.ndarray,
 (150,),
 1,
 150)

In [14]:
indices, indices.min(), indices.max()

(array([109,  74,  29,  96, 124,  71,  18, 125, 144,   7,   5, 118,   9,
         72, 111, 114,  37,  66, 137, 138,  56, 146, 135,  70,  25,  28,
         63,  60, 117,  33,   4,  55,  94,  44,  45,  26,  39, 139, 112,
          8, 113,  89,  90, 116,  88, 110,  24,  30, 103,  61,  87, 123,
         19, 145,  83,  54,  32,  16,  51,  86, 131,  40,  81,  22, 130,
        129, 136,  80,  98, 127,  27,  92, 108,  46,  67,  97,  62,   2,
         59, 141, 106,  43,  10,  93,  73,  21,  77, 122, 115, 101,  34,
         36,  50,   0, 107,  95,  64, 134,  41,  69,  49,  48,  85,  13,
        143,  23,  58, 126,  20,  15,  78, 104,  52, 100,  76,   3,  47,
        142,   6,  68,  75,  84, 140, 121,  12, 147,  99,  14, 148,  91,
         82,  11, 119, 102,  35,  57,  65,   1, 120,  31,  42, 105, 132,
         79,  17,  38, 133,  53, 149, 128]),
 0,
 149)

In [15]:
indices[:-10]

array([109,  74,  29,  96, 124,  71,  18, 125, 144,   7,   5, 118,   9,
        72, 111, 114,  37,  66, 137, 138,  56, 146, 135,  70,  25,  28,
        63,  60, 117,  33,   4,  55,  94,  44,  45,  26,  39, 139, 112,
         8, 113,  89,  90, 116,  88, 110,  24,  30, 103,  61,  87, 123,
        19, 145,  83,  54,  32,  16,  51,  86, 131,  40,  81,  22, 130,
       129, 136,  80,  98, 127,  27,  92, 108,  46,  67,  97,  62,   2,
        59, 141, 106,  43,  10,  93,  73,  21,  77, 122, 115, 101,  34,
        36,  50,   0, 107,  95,  64, 134,  41,  69,  49,  48,  85,  13,
       143,  23,  58, 126,  20,  15,  78, 104,  52, 100,  76,   3,  47,
       142,   6,  68,  75,  84, 140, 121,  12, 147,  99,  14, 148,  91,
        82,  11, 119, 102,  35,  57,  65,   1, 120,  31])

In [16]:
indices[-10:]

array([ 42, 105, 132,  79,  17,  38, 133,  53, 149, 128])

In [17]:
# method 2
from sklearn.model_selection import train_test_split
iris_x_train, iris_x_test, iris_y_train, iris_y_test = train_test_split(iris_x, iris_y, test_size=10)

In [18]:
iris_x_train, type(iris_x_train), iris_x_train.shape, iris_x_train.ndim, iris_x_train.size

(array([[5.7, 4.4, 1.5, 0.4],
        [6.3, 2.3, 4.4, 1.3],
        [5.8, 2.7, 5.1, 1.9],
        [5. , 2. , 3.5, 1. ],
        [4.9, 3.6, 1.4, 0.1],
        [5.8, 2.7, 3.9, 1.2],
        [7.3, 2.9, 6.3, 1.8],
        [6.1, 3. , 4.6, 1.4],
        [5.9, 3.2, 4.8, 1.8],
        [6.3, 2.5, 4.9, 1.5],
        [5.7, 3. , 4.2, 1.2],
        [5.8, 4. , 1.2, 0.2],
        [5.8, 2.8, 5.1, 2.4],
        [6.5, 3. , 5.5, 1.8],
        [5. , 3.6, 1.4, 0.2],
        [6. , 3. , 4.8, 1.8],
        [5.6, 2.9, 3.6, 1.3],
        [5.7, 2.6, 3.5, 1. ],
        [5.4, 3.4, 1.7, 0.2],
        [6.9, 3.1, 4.9, 1.5],
        [7.9, 3.8, 6.4, 2. ],
        [5. , 3.4, 1.6, 0.4],
        [4.3, 3. , 1.1, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5. , 3.4, 1.5, 0.2],
        [4.9, 2.4, 3.3, 1. ],
        [5.1, 3.8, 1.5, 0.3],
        [6.3, 3.3, 4.7, 1.6],
        [6.3, 2.7, 4.9, 1.8],
        [5.9, 3. , 5.1, 1.8],
        [5.7, 2.8, 4.5, 1.3],
        [5.8, 2.6, 4. , 1.2],
        [7.7, 3.8, 6.7, 2.2],
        [6

In [20]:
iris_y_train.shape

(140,)

In [19]:
KNeighborsClassifier?

In [23]:
knn = KNeighborsClassifier()  # 預設 n_neighbors=5
#定義一個 knn分類器物件
knn.fit(iris_x_train, iris_y_train)  
#調用該對象的訓練方法，主要接收兩個參數：訓練資料集及其樣本標籤

iris_y_predict = knn.predict(iris_x_test) 
#調用該物件的測試方法，主要接收一個參數：測試資料集
probability = knn.predict_proba(iris_x_test)  
#計算各測試樣本基於概率的預測
neighborpoint = knn.kneighbors(iris_x_test, n_neighbors=5, return_distance=False)
#計算與測試樣本距離在最近的5個點，返回的是這些樣本的序號組成的陣列
# knn.score?
score = knn.score(iris_x_test, iris_y_test, sample_weight=None)
#調用該物件的打分方法，計算出準確率

print('iris_y_predict = ')  
print(iris_y_predict)  
print('')
#輸出測試的結果

print('iris_y_test = ')
print(iris_y_test)    
#輸出原始測試資料集的正確標籤，以方便對比
print('Accuracy:', score) 
#輸出準確率計算結果

print('')
print('neighborpoint of test sample:', neighborpoint)
print('probability:', probability)


iris_y_predict = 
[2 2 1 0 1 1 2 0 2 1]

iris_y_test = 
[2 2 1 0 1 1 2 0 2 1]
Accuracy: 1.0

neighborpoint of test sample: [[119  55  53  33  46]
 [ 73  49  76  33  55]
 [ 88  42  35 121  97]
 [124 128  36 120 132]
 [ 35  19  57 109  88]
 [ 88  35  42 121  40]
 [ 61 125  13 126  87]
 [132 124  36 120  23]
 [ 46  55 126  53  13]
 [ 97  88  42 121 101]]
probability: [[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [24]:
knn.classes_

array([0, 1, 2])

In [25]:
# 檢視 source code
?? KNeighborsClassifier